config/routes.rb
Rails.application.routes.draw do
	# フロント
	scope module: 'front' do
		root 'home#index'
		get "/about",    to: "pages#about"
		resources :articles,          only: [:index, :show]
		resources :editors,           only: [:show]
		resources :notices,           only: [:index, :show]
		resources :contacts,          only: [:index, :create]
	end

	# 管理画面
	namespace :admin do
		root 'home#index'
		resources :articles,          only: [:index, :new, :create, :edit, :update, :destroy]
		resources :categories,        only: [:index, :create, :update, :destroy]
		resources :tags,              only: [:index, :create, :update, :destroy]
		resources :sliders,           only: [:index, :create]
		resources :pickup_articles,   only: [:index, :create]
		resources :editors,           only: [:index, :new, :create, :edit, :update, :destroy]
		resources :notices,           only: [:index, :new, :create, :edit, :update, :destroy]
		resources :contacts,          only: [:index, :show]
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :category
	belongs_to :editor
	has_many :article_tag_relations
	has_many :tags, through: :article_tag_relations

	has_one_attached :mv_image do |attachable|
		attachable.variant :thumb, resize_to_limit: [200, 200]
	end

	attr_accessor :mv_image_delete_flg

	# 公開状態
	STATUS__PUBLIC  = 1 # 公開
	STATUS__PRIVAYE = 2 # 非公開
	STATUS__DRAFT   = 3 # 下書き

	IMAGE_PATH_DEFAULT_MV_IMAGE = 'default/default_article_mv_image.jpg'

	validates :title,              presence: true, length: { maximum: 50 }
	validates :lead,               presence: true, length: { maximum: 500 }
	validates :content,            presence: true
	validates :mv_path,            presence: true
	validates :meta_title,         presence: true
	validates :meta_keyword,       presence: true
	validates :meta_description,   presence: true
	validates :category_id,        presence: true, numericality: { only_integer: true }
	validates :editor_id,          presence: true, numericality: { only_integer: true }
	validates :status,             presence: true, numericality: { only_integer: true }
	validates :slider_order,       presence: false, numericality: { only_integer: true }
	validates :pickup_order,       presence: false, numericality: { only_integer: true }

	validate :validate_check_public_datetime,  if: :public_datetime
	validate :validate_check_private_datetime, if: :private_datetime

	# MV画像
	def mv_image_path
		mv_image.attached? ? mv_image : IMAGE_PATH_DEFAULT_MV_IMAGE
	end

	# MV画像 (サムネ用)
	def mv_image_thumb_path
		mv_image.attached? ? mv_image.variant(:thumb) : IMAGE_PATH_DEFAULT_MV_IMAGE
	end

	private

	def validate_check_public_datetime
		errors.add(:public_datetime, "は現在の日時より後の日時にしてください") unless  Time.now < public_datetime
	end

	def validate_check_private_datetime
		if public_datetime
			errors.add(:private_datetime, "は非公開日時は公開日時より後の日時にしてください") unless public_datetime < private_datetime
		else
			errors.add(:private_datetime, "は現在の日時より後の日時にしてください") unless Time.now < private_datetime
		end
	end

end

app/models/article_tag_relation.rb
class ArticleTagRelation < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles

	validates :label, presence: true, length: {maximum: 10}
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/editor.rb
class Editor < ApplicationRecord
	has_many :articles

	validates :first_name,           presence: true, length: { maximum: 15 }
	validates :last_name,            presence: true, length: { maximum: 15 }
	validates :first_name_ruby,      presence: true, length: { maximum: 15 }
	validates :last_name_ruby,       presence: true, length: { maximum: 15 }
	validates :birthday,             presence: true
	validates :thumb_path,           presence: true
	validates :organization,         presence: true, length: { maximum: 20 }
	validates :position,             presence: true, length: { maximum: 20 }
	validates :lead,                 presence: true, length: { maximum: 30 }
	validates :introduction,         presence: true, length: { maximum: 500 }

	def full_name
		first_name + last_name
	end

end

app/models/notice.rb
class Notice < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :article_tag_relations
	has_many :articles, through: :article_tag_relations
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController

	before_action :target_article,   only: [:edit, :update, :destroy]

	def index
		@Articles = Article.all
	end

	def new
		@Form = Forms::Admin::ArticleForm.new
	end

	def edit
		@Form = Forms::Admin::ArticleForm.new(article: @target_article)
	end

	def create
		@Form = Forms::Admin::ArticleForm.new(attributes: article_form_params)
		if @Form.save
			redirect_to admin_article_path(:id), notice: "User was successfully created."
		else
			render :new, status: :unprocessable_entity
		end
	end

	def update
		@Form = Forms::Admin::ArticleForm.new(attributes: article_form_params, article: @target_article)
		if @Form.save
			redirect_to admin_article_path(:id), notice: "User was successfully created."
		else
			render :edit, status: :unprocessable_entity
		end
	end

	def destroy
		@target_article.delete
		redirect_to admin_articles_path
	end

	private

	def article_form_params
		params.require(:forms_admin_article_form).permit(article_attributes: [
																	:title,
																	:lead,
																	:content,
																	:status,
																	:mv_path,
																	:meta_title,
																	:meta_keyword,
																	:meta_description,
																	:public_datetime,
																	:private_datetime,
																	:category_id,
																	:editor_id,
																	:mv_image,
																	:mv_image_delete_flg,
																	tag_ids: []]
																)
	end

	def target_article
		@target_article = Article.find(params[:id])
	end
end

app/controllers/admin/contacts_controller.rb
class Admin::ContactsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/admin/editors_controller.rb
class Admin::EditorsController < ApplicationController
	def index
		@Editors = Editor.all
	end

	def new
		@Editor = Editor.new
	end

	def create
		editor = Editor.new(editor_params)
		if editor.save
			redirect_to admin_editors_path
		else
			redirect_to admin_editors_path
		end
	end

	def update
	end

	def destroy
		editor = Editor.find(params[:id])
		editor.delete
		redirect_to admin_editors_path
	end

	private
	def editor_params
		params.require(:editor).permit(:first_name,
										:last_name,
										:first_name_ruby,
										:last_name_ruby,
										:birthday,
										:thumb_path,
										:organization,
										:position,
										:lead,
										:introduction)
	end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
  def index
	redirect_to admin_articles_path
  end
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/admin/sliders_controller.rb
class Admin::SlidersController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
	def index
		@Tags = Tag.all
		@Tag = Tag.new
	end

	def create
		tag = Tag.new(tag_params)
		if tag.save
			redirect_to admin_tags_path
		else
			redirect_to admin_tags_path
		end
	end

	def update
	end

	def destroy
		tag = Tag.find(params[:id])
		tag.delete
		redirect_to admin_tags_path
	end

	private
	def tag_params
		params.require(:tag).permit(:label)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/front/articles_controller.rb
class Front::ArticlesController < ApplicationController
  def index
  end

  def show
  end	
end

app/controllers/front/contacts_controller.rb
class Front::ContactsController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/front/editors_controller.rb
class Front::EditorsController < ApplicationController
  def show
  end
end

app/controllers/front/home_controller.rb
class Front::HomeController < ApplicationController
  def index
	@test = 'test'
  end
end

app/controllers/front/notices_controller.rb
class Front::NoticesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/front/pages_controller.rb
class Front::PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/articles/_article.html.erb
<li>
	<%= article.title %>
	<%= link_to "編集", edit_admin_article_path(article) %> 
	<%= link_to "削除", [:admin, article], data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %> 
</li>

app/views/admin/articles/_form.erb
<% article_form # @param [ArticleForm] article_form %>
<%= form_with(model: article_form, url: article_form.persisted? ? admin_article_path(article_form) : admin_articles_path) do |form| %>
  <% if article_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article_form.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article_form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  # articles
  <%= form.fields_for(:article_attributes, article_form.article) do |article_fields| %>
	<%= article_fields.label :editor_id %>
	<%= article_fields.collection_select :editor_id, Editor.all, :id, :first_name, required: true %>
	<br>

	<%= article_fields.label :status %>
	<%= article_fields.select :status, Forms::Admin::ArticleForm.status_options, required: true %>
	<br>

	<%= article_fields.label :category_id %>
	<%= article_fields.collection_select :category_id, Category.all, :id, :label, required: true %>
	<br>

	<%= article_fields.label :public_datetime %>
	<%= article_fields.datetime_field :public_datetime %>
	<br>

	<%= article_fields.label :private_datetime %>
	<%= article_fields.datetime_field :private_datetime %>
	<br>

	<%= article_fields.label :meta_title %>
	<%= article_fields.text_field :meta_title, required: true %>
	<br>

	<%= article_fields.label :meta_keyword %>
	<%= article_fields.text_field :meta_keyword, required: true %>
	<br>

	<%= article_fields.label :meta_description %>
	<%= article_fields.text_field :meta_description %>
	<br>

	MV画像アップ<br>
	<%= article_fields.file_field :mv_image, accept: "image/jpeg,image/gif,image/png" %>
	<% if article_form.article.mv_image.attached? %>
		<br>
		<%= article_fields.label :mv_image_delete_flg %>
		<%= article_fields.check_box :mv_image_delete_flg, { multiple: false }, checked_value = "1", unchecked_value = "0" %>
	<% end %>
	<br>
	<%= image_tag article_form.article.mv_image_thumb_path %>
	<br>

	<%= article_fields.label :title %>
	<%= article_fields.text_field :title, required: true %>
	<br>

	<%= article_fields.label :lead %>
	<%= article_fields.text_area :lead %>
	<br>
	
	<%= article_fields.label :content %>
	<%= article_fields.text_area :content %>
	<br>

	# tags
	<%= article_fields.collection_check_boxes :tag_ids, Tag.all, :id, :label, include_hidden: false do |b| %>
		<%= b.check_box %>
		<%= b.label %>
	<% end %>
  <% end %>

  <hr>

	<%= form.submit "Save changes" %>
<% end %>

app/views/admin/articles/create.html.erb
<h1>Admin::Articles#create</h1>
<p>Find me in app/views/admin/articles/create.html.erb</p>

app/views/admin/articles/destroy.html.erb
<h1>Admin::Articles#destroy</h1>
<p>Find me in app/views/admin/articles/destroy.html.erb</p>

app/views/admin/articles/edit.html.erb
<h1>Admin::Articles#edit</h1>
<p>Find me in app/views/admin/articles/edit.html.erb</p>

<%= render 'form', article_form: @Form %>

app/views/admin/articles/index.html.erb
<h1>Admin::Articles#index</h1>
<p>Find me in app/views/admin/articles/index.html.erb</p>
<ul>
	<%= render @Articles %>
</ul>

app/views/admin/articles/new.html.erb
<h1>Admin::Articles#new</h1>
<p>Find me in app/views/admin/articles/new.html.erb</p>

<%= render 'form', article_form: @Form %>

app/views/admin/articles/update.html.erb
<h1>Admin::Articles#update</h1>
<p>Find me in app/views/admin/articles/update.html.erb</p>

<%= render 'form', article_form: @Form %>

app/views/admin/editors/_editor.html.erb
<li>
	<%= editor.full_name %>
	<%= link_to "削除", [:admin, editor], data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %> 
</li>

app/views/admin/editors/create.html.erb
<h1>Admin::Editors#create</h1>
<p>Find me in app/views/admin/editors/create.html.erb</p>

app/views/admin/editors/destroy.html.erb
<h1>Admin::Editors#destroy</h1>
<p>Find me in app/views/admin/editors/destroy.html.erb</p>

app/views/admin/editors/edit.html.erb
<h1>Admin::Editors#edit</h1>
<p>Find me in app/views/admin/editors/edit.html.erb</p>

app/views/admin/editors/index.html.erb
<h1>Admin::Editors#index</h1>
<p>Find me in app/views/admin/editors/index.html.erb</p>

<ul>
	<%= render @Editors %>
</ul>

app/views/admin/editors/new.html.erb
<h1>Admin::Editors#new</h1>
<p>Find me in app/views/admin/editors/new.html.erb</p>

<%= form_with(model: [:admin, @Editor], local: true) do |f| %>
	<%= f.label :first_name %>
	<%= f.text_field :first_name %>
	<br>

	<%= f.label :last_name %>
	<%= f.text_field :last_name %>
	<br>

	<%= f.label :first_name_ruby %>
	<%= f.text_field :first_name_ruby %>
	<br>

	<%= f.label :last_name_ruby %>
	<%= f.text_field :last_name_ruby %>
	<br>

	<%= f.label :birthday %>
	<%= f.date_field :birthday %>
	<br>

	# 画像アップ
	<%= f.label :thumb_path %>
	<%= f.text_field :thumb_path %>
	<br>

	<%= f.label :organization %>
	<%= f.text_field :organization %>
	<br>

	<%= f.label :position %>
	<%= f.text_field :position %>
	<br>

	<%= f.label :lead %>
	<%= f.text_field :lead %>
	<br>

	<%= f.label :introduction %>
	<%= f.text_area :introduction %>
	<br>
	
	<%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/admin/editors/update.html.erb
<h1>Admin::Editors#update</h1>
<p>Find me in app/views/admin/editors/update.html.erb</p>

app/views/admin/notices/create.html.erb
<h1>Admin::Notices#create</h1>
<p>Find me in app/views/admin/notices/create.html.erb</p>

app/views/admin/notices/destroy.html.erb
<h1>Admin::Notices#destroy</h1>
<p>Find me in app/views/admin/notices/destroy.html.erb</p>

app/views/admin/notices/edit.html.erb
<h1>Admin::Notices#edit</h1>
<p>Find me in app/views/admin/notices/edit.html.erb</p>

app/views/admin/notices/index.html.erb
<h1>Admin::Notices#index</h1>
<p>Find me in app/views/admin/notices/index.html.erb</p>

app/views/admin/notices/new.html.erb
<h1>Admin::Notices#new</h1>
<p>Find me in app/views/admin/notices/new.html.erb</p>

app/views/admin/notices/update.html.erb
<h1>Admin::Notices#update</h1>
<p>Find me in app/views/admin/notices/update.html.erb</p>